name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for code factor
        run: |
          # Add your code factor check command here
          echo "Code factor check passed"

      - name: Check for conflicts with base branch
        run: |
          git fetch origin
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-commit --no-ff ${{ github.event.pull_request.head.ref }}
          git merge --abort || { echo "Merge conflict detected"; exit 1; }

  auto_merge:
    needs: run_checks
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
